apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-role-binding-k8s-restart-notify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role-k8s-restart-notify
subjects:
  - kind: ServiceAccount
    name: k8s-restart-notify
    namespace: <YOUR_NAMESPACE>
