apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <YOUR_NAMESPACE>

labels:
  - pairs:
      app: k8s-restart-notify
    includeSelectors: true
    includeTemplates: true

resources:
  - namespace.yaml
  - deployment.yaml
  - sa.yaml
  - cluster_role.yaml
  - cluster_role_binding.yaml
